### ISSUE TITLE
not compatible with Python2.7 or Python 3.8?

### ISSUE THREAD

**Issue by docfate111** [Jakeler/adb-root#3]
```
Traceback (most recent call last):
  File "adb-root.py", line 72, in <module>
    pull()
  File "adb-root.py", line 60, in pull
    result = subprocess.run(['adb', 'shell', "su -c", "dd if="+args.source], stdout=file)
AttributeError: 'module' object has no attribute 'run'
```

**Comment by Jakeler** [comment]
It should be compatible with python >= 3.5 so for example 3.8.
You should not use python 2 anymore, since it is eol.
